### ISSUE TITLE
Set up Dependabot

### ISSUE THREAD

**Issue by paulmelnikow** [mathisonian/react-editable-svg-label#10]
Hey @mathisonian, what do you think about setting up Dependabot for this repo? I've had excellent experience with it on other project and found that the prompting helps me keep things up to date. I'd be down to tackle the alerts as they come in, time permitting.

**Comment by mathisonian** [comment]
I haven't used it before, but just added the project to Dependabot. It seems like a cool tool, looking forward to seeing it in action. Let me know if there's anything else you need me to do in terms of config for this.

**Comment by paulmelnikow** [comment]
Sounds good! Yea, I think we can just let it run, and tweak the settings down the line if need be. Thanks!
