### ISSUE TITLE
Build example apps for PR review

### ISSUE THREAD

**Issue by paulmelnikow** [mathisonian/react-editable-svg-label#23]
I'd like to set something up to build the example app in PRs. It makes it quick and easy to review dependency updates like #21.

I did something similar in another project. The example app doesn't look as nice as this one, but you can see how it gets built and linked to from the PR: paulmelnikow/react-boxplot#49

That's using Zeit Now, which is a pretty easy way to go, though there are other options like Netlify.

If you'd like to try the Zeit route, the easiest way to start is to create an account at http://zeit.co/ and turn on the GitHub integration. You can limit which repos it gets access to.

**Comment by mathisonian** [comment]
Done!

**Comment by paulmelnikow** [comment]
These don't seem to be working quite right:

<img width="792" alt="screen shot 2018-12-11 at 4 56 15 pm" src="https://user-images.githubusercontent.com/1487036/49832795-b1202c00-fd65-11e8-9091-7fdb0a628ee0.png">


I can look into it.
