### ISSUE TITLE
Update build tools for Node 8+

### ISSUE THREAD

**Issue by paulmelnikow** [mathisonian/react-editable-svg-label#5]
`react-component-gulp-tasks` is not being maintained; see JedWatson/react-component-gulp-tasks#31.

The build still runs in Node 6.

**Comment by mathisonian** [comment]
It looks like there is a fix available via https://github.com/JedWatson/react-component-gulp-tasks/pull/30

However, as you note, the project doesn't seem to be merging any PRs. A band-aid solution could be to fork that project with the patch applied and point the dependency to the fork. Ideally we would drop the dependency altogether though, and replace with webpack or rollup.

**Comment by paulmelnikow** [comment]
I don't have a ton of experience using webpack or rollup directly, though I've used [create-react-library](https://github.com/transitive-bullshit/create-react-library) and could either use that or mimic the way it's using rollup.

As a band-aid, I think we could run the build in Node 6 easily enough.

**Comment by paulmelnikow** [comment]
I started a branch: https://github.com/mathisonian/react-editable-svg-label/compare/777b03d4690913f96d1fbe4a465e72ddf6e913b8...rollup

The library building is working well (`lib/` and `dist/`) but the examples bit isn't quite working yet. In Rollup you can use two features, `experimentalCodeSplitting` and `manualChunks`, to accomplish something similar to the way `react-component-gulp-tasks` built the examples. However the output needs to be in ES Modules or SystemJS. SystemJS requires bootstrapping the SystemJS dependency, though I'm thinking that is a good way to go. Other alternatives are to build one big bundle for the example app, or to bootstrap React and react-portal, and build a small bundle.

I haven't tackled minifying of `dist/` yet. Do you think that's needed?

Feel free to push commits to that branch if you'd like.

**Comment by paulmelnikow** [comment]
I'm running into what seems like an esoteric issue with SystemJS: systemjs/systemjs#1884. Will see how they respond.

I did find a promising alternative to `react-component-gulp-tasks` called [microbundle]( https://github.com/developit/microbundle), and while that project is merging pull requests, development seems a bit stalled. See developit/microbundle#39 which is about a major transition from Bublé to Babel. Might be worth a test drive, as rolling our own rollup is turning out to be a good bit of effort.

**Comment by paulmelnikow** [comment]
I started a discussion about extracting reusable build scripts in transitive-bullshit/create-react-library#104, and asked for an update about the Babel support in microbundle at https://github.com/developit/microbundle/pull/39#issuecomment-443866637.

IMO it's not worth adopting microbundle until the Babel support is shipped. I'm eager to get this working in Node 10 so maybe we could merge the rollup work I did and revisit microbundle at a later date. Would you like to take a look?

**Comment by mathisonian** [comment]
Rollup builds make a lot of sense to me 👍
