### ISSUE TITLE
Reduce frequency of Dependabot bumps

### ISSUE THREAD

**Issue by paulmelnikow** [mathisonian/react-editable-svg-label#75]
Hi @mathisonian, what would you think about configuring Dependabot to check for updates monthly instead of daily? I don't have access, though there's a place in the UI where you can adjust that setting: https://app.dependabot.com/accounts/mathisonian

**Comment by mathisonian** [comment]
Yeah that seems more manageable. Updated.

**Comment by paulmelnikow** [comment]
Thanks!
